apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluephish
commonLabels:
  app.kubernetes.io/name: bluephish
resources:
  - ns.yaml
  - ingress.yaml
  - service.yaml
  - statefulset.yaml