# sample docker-compose.yaml for a BluePhish deployment
version: '3'
services:
  app:
    container_name: bluephish
    image: dockerbluestone/bluephish:latest
    ports:
      - 3333:3333
      - 8080:80
    volumes:
      - /data/bluephish/gophish.db:/opt/gophish-v0.11.0/gophish.db
    restart: unless-stopped
    networks:
      - bluephish

networks:
  bluephish:
    driver: bridge