name: CI
on: 
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.17]

    steps:
    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.goVer }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get gopkg.in/check.v1

    - name: Build
      run: go build -v .
    
    # - name: Format
    #   run: diff -u <(echo -n) <(gofmt -d .)
    
    - name: Test
      run: go test -v ./...

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force